package com.chubby.dolphin.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * FatigueAlert — Tracks creative fatigue detection events.
 * Generated by CreativeFatigueService when CTR, Frequency, or CPM
 * degrades below acceptable thresholds for a campaign's active creative.
 */
@Entity
@Table(name = "fatigue_alerts", indexes = {
    @Index(name = "idx_fatigue_campaign",  columnList = "campaign_id"),
    @Index(name = "idx_fatigue_workspace", columnList = "workspace_id"),
    @Index(name = "idx_fatigue_status",    columnList = "status")
})
public class FatigueAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private String campaignId;

    private String creativeId;
    private String workspaceId;

    /** CTR, FREQUENCY, CPM */
    @Column(nullable = false)
    private String fatigueType;

    private Double baselineCtr;
    private Double currentCtr;
    private Double baselineFreq;
    private Double currentFreq;
    private Double baselineCpm;
    private Double currentCpm;

    @Column(nullable = false)
    private LocalDateTime detectedAt = LocalDateTime.now();

    private LocalDateTime resolvedAt;

    /** PENDING, ROTATED, ACKNOWLEDGED */
    @Column(nullable = false)
    private String status = "PENDING";

    private LocalDateTime createdAt = LocalDateTime.now();
    private LocalDateTime updatedAt = LocalDateTime.now();

    public FatigueAlert() {}

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getCampaignId() { return campaignId; }
    public void setCampaignId(String campaignId) { this.campaignId = campaignId; }
    public String getCreativeId() { return creativeId; }
    public void setCreativeId(String creativeId) { this.creativeId = creativeId; }
    public String getWorkspaceId() { return workspaceId; }
    public void setWorkspaceId(String workspaceId) { this.workspaceId = workspaceId; }
    public String getFatigueType() { return fatigueType; }
    public void setFatigueType(String fatigueType) { this.fatigueType = fatigueType; }
    public Double getBaselineCtr() { return baselineCtr; }
    public void setBaselineCtr(Double baselineCtr) { this.baselineCtr = baselineCtr; }
    public Double getCurrentCtr() { return currentCtr; }
    public void setCurrentCtr(Double currentCtr) { this.currentCtr = currentCtr; }
    public Double getBaselineFreq() { return baselineFreq; }
    public void setBaselineFreq(Double baselineFreq) { this.baselineFreq = baselineFreq; }
    public Double getCurrentFreq() { return currentFreq; }
    public void setCurrentFreq(Double currentFreq) { this.currentFreq = currentFreq; }
    public Double getBaselineCpm() { return baselineCpm; }
    public void setBaselineCpm(Double baselineCpm) { this.baselineCpm = baselineCpm; }
    public Double getCurrentCpm() { return currentCpm; }
    public void setCurrentCpm(Double currentCpm) { this.currentCpm = currentCpm; }
    public LocalDateTime getDetectedAt() { return detectedAt; }
    public void setDetectedAt(LocalDateTime detectedAt) { this.detectedAt = detectedAt; }
    public LocalDateTime getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(LocalDateTime resolvedAt) { this.resolvedAt = resolvedAt; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
