apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dolphinal
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - minio.yaml
  - backend.yaml
  - frontend.yaml
  - gateway.yaml
  - observability.yaml
